"""users and document ownership

Revision ID: 600e0e3a8c6f
Revises: 16947631db6d
Create Date: 2026-08-12 22:45:05.324586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600e0e3a8c6f'
down_revision: Union[str, Sequence[str], None] = '16947631db6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    # Documents uploaded before authentication existed have no owner, and there
    # is nobody to assign them to. A NOT NULL column cannot be added while they
    # are present, and leaving them ownerless would make them unreachable by
    # their uploader yet visible to any query that forgot to filter. Chunks and
    # pages follow via ON DELETE CASCADE.
    op.execute("DELETE FROM documents")

    op.add_column('documents', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # Named explicitly: autogenerate leaves this as None, which makes the
    # downgrade fail because it cannot identify the constraint to drop.
    op.create_foreign_key(
        'fk_documents_user_id', 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_user_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_column('documents', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
